FROM purplei2p/i2pd:latest

USER root
RUN apk add --no-cache gettext

COPY i2pd.conf.template /i2pd.conf.template
COPY entrypoint.sh /entrypoint.sh

# Pre-create paths, assign ownership, and make script executable
RUN mkdir -p /shared_certs /var/lib/i2pd/certificates/reseed /var/lib/i2pd/netDb && \
    chown -R 1000:1000 /var/lib/i2pd /shared_certs && \
    chmod +x /entrypoint.sh

USER 1000
ENTRYPOINT ["/entrypoint.sh"]
