# Node Configuration
# General Options
ipv4 = true
ipv6 = false
netid = $NET_ID
floodfill = true
port = $PORT
address4 = 127.0.0.1

reservedrange = false
nat = false
notransit = false
log = file
logfile = $NODE_DIR/i2pd.log
loglevel = debug

[reseed]
urls = ""

[http]
enabled = true
address = 127.0.0.1
port = $HTTP_PORT

[httpproxy]
enabled = true
address = 127.0.0.1
port = $H_PROXY

[socksproxy]
enabled = true
address = 127.0.0.1
port = $S_PROXY

[sam]
enabled = false
